<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
    <title><%=[page.getValue title]%></title>
    <link rel="stylesheet" type="text/css" href="/stats/inc/styles.css">
    <script type="text/javascript">
        djConfig = {
            isDebug: <%=[page.getValue debug]%>
        };
    </script>
    <script src="/stats/dojo/dojo.js"></script>
    <script src="/stats/inc/javascript.js"></script>
</head>
<body>
